FRW-42 DevVM Deprecation
spryker/devvm pull request #94
Opened 2022-07-07 12:36 UTC by geega

## PR Description

https://spryker.atlassian.net/browse/FRW-42

2022-07-12 13:00 UTC, asmarovydlo requested changes
The default branch for the repository is not master, please provide the PR there.

2022-07-12 13:00 UTC, asmarovydlo commented on README.md
> +**DEPRECATED**
Please a message that docker should be used instead, and the link to the documentation.

2022-07-13 11:27 UTC, asmarovydlo commented
https://github.com/spryker/devvm/pull/94#pullrequestreview-1035497585 
Currently, the PR have conflicts, because those branches have different readme file.
Please create 2 PR's (keep this one for `master` branch), and create another one for `develop`.

2022-07-13 12:25 UTC, geega commented
Created https://github.com/spryker/devvm/pull/95

2022-08-02 12:34 UTC, asmarovydlo approved these changes

2022-08-10 12:47 UTC, closed without merging